apiVersion: v1
kind: Pod
metadata:
  name: busybox-demo
  namespace: share-app   
  labels:
    app: busybox-demo
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["sh", "-c", "echo Hello from BusyBox && sleep 3600"]